### ISSUE TITLE
Python error in OS X: 'Gridgen' object has no attribute '_libgridgen'

### ISSUE THREAD

**Issue by ForTozs** [hetland/pygridgen#26]
Hi guys. I appreciate all the hard work y'all put into this project. I am new to ROMS with some Python background, so I thought I'd give PyROMS/pygridgen a try. I was able to build nn, csa, gridutils, and gridgen, but I have not been able to use pygridgen successfully. When following the first example I get:

    >>> grid = pygridgen.grid.Gridgen(x, y, beta, shape=(10, 5))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pygridgen/grid.py", line 767, in __init__
        self._libgridgen.gridgen_generategrid2.restype = ctypes.c_void_p
    AttributeError: 'Gridgen' object has no attribute '_libgridgen'

This seems related to a recent ticket on here that seems to have been resolved. I also saw something related to this here:

https://www.myroms.org/forum/viewtopic.php?f=14&t=3650#p13888

I guess I should give you some details about my build, because it could be related to this. I am running OS X El Cap. I am using macports for some dependencies (python27, numpy, matplotlib) so I have installed all the libraries in `/opt/local`. I'm not sure if this could create a conflict, but I have been trying to get away from `/usr/local`. I had trouble compiling the dependency libraries from `/external` so I built from these sources (which could also be the root of my problem):

git clone https://github.com/sakov/nn-c
git clone https://github.com/sakov/csa-c
git clone https://github.com/sakov/gridutils-c
git clone https://github.com/sakov/gridgen-c
git clone https://github.com/phobson/pygridgen

Dr. Hetland's master gave me a different issue for pygridgen:

    >>> import pygridgen
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pygridgen/__init__.py", line 16, in <module>
        from csa import *
      File "pygridgen/csa.py", line 9, in <module>
        class csa(object):
      File "pygridgen/csa.py", line 62, in csa
        _csa = np.ctypeslib.load_library('_csa', path)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/ctypeslib.py", line 128, in load_library
        raise OSError("no file with expected extension")
    OSError: no file with expected extension

All signs seem to be pointing to improperly building the dependencies, but I don't really know. The binaries run fine from the command line. I only rarely compile from source, so I could be overlooking something simple. Does anyone know what my issue could be? Any help would be greatly appreciated.

**Comment by ForTozs** [comment]
Yep. Rookie mistake. I needed to copy the shared .so files into `/opt/local/lib/python2.7/site-packages/pygridgen/` folder (I had to create the folder). Pretty hackish, I'm sure there's a proper way to do it, but at least it works now.
